// Code generated by cmd/cgo; DO NOT EDIT.

//line /home/robin/Projects/golang/go-learn/day12/cgo.go:1:1
package main

//int add(int a, int b);
import _ "unsafe"

//export add
func add(a, b  /*line :7:15*/_Ctype_int /*line :7:20*/)  /*line :7:22*/_Ctype_int /*line :7:27*/ {
	return a + b
}

func main() {}
